package br.com.cidandrade.aula.gui;

import br.com.cidandrade.aula.dao.ConhecidoDAO;
import br.com.cidandrade.aula.dao.ContatoDAO;
import br.com.cidandrade.aula.entidade.Conhecido;
import br.com.cidandrade.aula.entidade.Contato;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class AgendaGUI extends javax.swing.JFrame {

    /**
     * Creates new form AgendaGUI
     */
    public AgendaGUI() {
        initComponents();
        String[] camposConhecido = {"ID", "Nome", "Referencia"};
        List<Conhecido> conhecidos = ConhecidoDAO.selecionarTodos();
        String[][] dadosConhecidos;
        dadosConhecidos = new String[conhecidos.size()][3];
        int posicao = 0;
        for (Conhecido c : conhecidos) {
            String[] umConhecido = new String[3];
            umConhecido[0] = String.valueOf(c.getId());
            umConhecido[1] = c.getNome();
            umConhecido[2] = c.getReferencia().getReferencia();
            dadosConhecidos[posicao++] = umConhecido;
        }
        DefaultTableModel modelo = new DefaultTableModel(
                dadosConhecidos, camposConhecido);
        jtConhecidos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jtpAbas = new javax.swing.JTabbedPane();
        jpConhecidos = new javax.swing.JPanel();
        jscpConhecidos = new javax.swing.JScrollPane();
        jtConhecidos = new javax.swing.JTable();
        jpContatos = new javax.swing.JPanel();
        jscpContatos = new javax.swing.JScrollPane();
        jtContatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtConhecidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscpConhecidos.setViewportView(jtConhecidos);

        javax.swing.GroupLayout jpConhecidosLayout = new javax.swing.GroupLayout(jpConhecidos);
        jpConhecidos.setLayout(jpConhecidosLayout);
        jpConhecidosLayout.setHorizontalGroup(
            jpConhecidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConhecidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpConhecidos, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );
        jpConhecidosLayout.setVerticalGroup(
            jpConhecidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConhecidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpConhecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpAbas.addTab("Conhecido", jpConhecidos);

        jtContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtContatos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtContatosFocusGained(evt);
            }
        });
        jscpContatos.setViewportView(jtContatos);

        javax.swing.GroupLayout jpContatosLayout = new javax.swing.GroupLayout(jpContatos);
        jpContatos.setLayout(jpContatosLayout);
        jpContatosLayout.setHorizontalGroup(
            jpContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpContatos, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );
        jpContatosLayout.setVerticalGroup(
            jpContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpAbas.addTab("Contato", jpContatos);

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpAbas))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpAbas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtContatosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtContatosFocusGained
        int selecionado = jtConhecidos.getSelectedRow();
        if (selecionado >= 0) {
            String idString = (String) jtConhecidos.getValueAt(
                    selecionado, 0);
            int id = Integer.parseInt(idString);
            String[] camposContato = {"Tipo", "Contato"};
            List<Contato> contatos
                    = ContatoDAO.selecionarPorConhecido(id);
            String[][] dadosContatos = new String[contatos.size()][2];
            int posicao = 0;
            for (Contato cont : contatos) {
                String[] umContato = new String[2];
                umContato[0] = cont.getTipo().getTipoContato();
                umContato[1] = cont.getIdentificacao();
                dadosContatos[posicao++] = umContato;
            }
            DefaultTableModel modelo = new DefaultTableModel(
                    dadosContatos, camposContato);
            jtContatos.setModel(modelo);
        } else {
            jtpAbas.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jtContatosFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpConhecidos;
    private javax.swing.JPanel jpContatos;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JScrollPane jscpConhecidos;
    private javax.swing.JScrollPane jscpContatos;
    private javax.swing.JTable jtConhecidos;
    private javax.swing.JTable jtContatos;
    private javax.swing.JTabbedPane jtpAbas;
    // End of variables declaration//GEN-END:variables
}
